### ISSUE TITLE
SignalR & Azure App Service Memory Usage

### ISSUE THREAD

**Issue by swaminathan-ramani** [analogrelay/analogrelay#2]
Hi Andrew, 

Hope you are doing well. I wanted to seek your help to resolve one of issue we are facing. We use SignalR in one of our enterprise grade applications. We are facing few challenges in Memory consumption. We have hosted signalr on Azure App service which is configured to scale based on memory. Currently the app service is scaling to 7 instances. Upon taking a memory dump there are two set of snapshots 

Snapshot 1: Shows LocalKeyEventInfo and ScaleoutMapping remain in memory
![image](https://user-images.githubusercontent.com/12950101/115767832-28027080-a3c7-11eb-9574-5023ac2e200d.png)
Snapshot 2: Refered from
![image](https://user-images.githubusercontent.com/12950101/115768849-76fcd580-a3c8-11eb-9930-9c21a58a286d.png)

Snapshot 3:
![image](https://user-images.githubusercontent.com/12950101/115769479-381b4f80-a3c9-11eb-894c-dfa43e26c7ed.png)
![image](https://user-images.githubusercontent.com/12950101/115769688-70bb2900-a3c9-11eb-83a9-f17f9e49e252.png)

If you can share some guidance on how we could resolve this it would really help us.

SignalR Libraries File version 
![image](https://user-images.githubusercontent.com/12950101/115773064-7f0b4400-a3cd-11eb-817a-0fc5f429add7.png)
Microsoft.AspNet.SignalR.Core.dll - File version 2.2.50714.868

Thanks
Sam

**Comment by analogrelay** [comment]
Hey @swami1106 !

I don't work on the SignalR team anymore so I don't really have the current context on things there, so I'd suggest reaching out to the experts on the team by filing an issue at https://github.com/SignalR/SignalR/ . 

The first thing that comes to mind here though is that SignalR keeps a buffer of all messages it sends (up to a maximum of 1000 per hub per connection) in order to support re-delivering messages that failed to be delivered. If you aren't seeing issues with clients frequently disconnecting and reconnecting (the `slowConnection` event on the client indicates this) then you could reduce this significantly and get improved memory usage at the cost of less reliability in the event that the connection drops and restarts. There's more guidance on SignalR performance [in the docs](https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/signalr-performance#tuning-your-signalr-server-for-performance) and I'd recommend taking a look at that as well.

Hope those links help out!
